/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "mmr_multican.h"
#include "Bsp.h"
#include  "lib/pin/inc/aurix_pin.h"


#define WAIT_TIME   1000                                                    /* Wait time constant in milliseconds   */


IfxCpu_syncEvent g_cpuSyncEvent = 0;




int core0_main(void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);



    // Inizializza la struttura dati

    uint8_t message_payload[8] = {'P','R', 'O', 'V', 'A' , ' ', 'A', 'U'};


    MmrCanMessage message;
    message.id      = 0x777;
    message.length  = 8;
    message.payload = message_payload;


    //Inizializza due led che permettono di avere un feedback visivo

    MmrPin led_tx = MMR_Pin(&MODULE_P33, 10, TRUE);
    MmrPin led_rx = MMR_Pin(&MODULE_P33, 11, TRUE);

/*
    g_led.led1.port      = &MODULE_P33;
    g_led.led1.pinIndex  = 10;
    g_led.led1.mode      = IfxPort_OutputIdx_general;
    g_led.led1.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    g_led.led2.port      = &MODULE_P33;
    g_led.led2.pinIndex  = 11;
    g_led.led2.mode      = IfxPort_OutputIdx_general;
    g_led.led2.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

/*

    /* Initialize the pins connected to LEDs to level "HIGH"; will keep the LEDs turned off as default state */
    //IfxPort_setPinHigh(g_led.led1.port, g_led.led1.pinIndex);
    //IfxPort_setPinHigh(g_led.led2.port, g_led.led2.pinIndex);
    MMR_PIN_write(&led_tx, MMR_PIN_LOW);
    MMR_PIN_write(&led_rx, MMR_PIN_LOW);

   /* Set the pin input/output mode for both pins connected to the LEDs */
    IfxPort_setPinModeOutput(led_tx.port, led_tx.pin, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(led_rx.port, led_rx.pin, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

   /* Set the pad driver mode for both pins connected to the LEDs */
    IfxPort_setPinPadDriver(led_tx.port, led_tx.pin, IfxPort_PadDriver_cmosAutomotiveSpeed1);
    IfxPort_setPinPadDriver(led_rx.port, led_rx.pin, IfxPort_PadDriver_cmosAutomotiveSpeed1);



    MMR_init_multican(led_tx, led_rx);        //Inizializza ricecvitore e trasmettitore CAN
    MMR_transmit_message(&message);     //Trasmette un messaggio



    //Se tutto il processo ha successo i due led dovrebbero accendersi

    MMR_transmit_message(&message);

    while(1)
    {

    }
    return (1);
}





//For Testing


